name: ci_meson

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends pkg-config gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libparmetis-dev

    - run: meson setup build
      env:
        FC: gfortran

    - run: meson compile -C build

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: brew install pkg-config gcc ninja scalapack

    - run: pip install meson

    - run: meson setup build
      env:
        FC: gfortran

    - run: meson compile -C build

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt
